[client]
maxUploadSize = 2000  # 2000 MB = 2GB (permite subir Inventario_v4 completo)
showErrorDetails = true
toolbarMode = "developer"
initialSidebarState = "collapsed"

[logger]
level = "info"

[server]
headless = true
port = 8501
enableXsrfProtection = true
